FROM busybox

# Set working directory
WORKDIR /tmp

# Download the script from GitHub
RUN wget https://raw.githubusercontent.com/rebootuser/LinEnum/master/LinEnum.sh -O /tmp/LinEnum.sh

# Make the script executable
RUN chmod +x /tmp/LinEnum.sh

# Run the script when container starts
CMD ["/tmp/LinEnum"]
