apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mal-con
  name: mal-con
spec:
  containers:
  - image: hreed014/cdr-xsiam-pc:latest
    name: mal-con
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
