apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bbxdr
  name: bbxdr
spec:
  containers:
  - image: busybox
    name: bbxdr
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
