# Dockerfile to run and execute the malicious-container.sh script inside a container

# Use a base image that includes a shell environment
FROM ubuntu:20.04

# Set environment variables to minimize interaction during installation
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install necessary packages
RUN apt-get update && \
    apt-get install -y curl bash && \
    rm -rf /var/lib/apt/lists/*

# Create a working directory for scripts
WORKDIR /tmp

# Copy the malicious script from the repository and download to the /tmp directory
ADD https://github.com/hankthebldr/xsiam-prisma-cdr-lab/blob/1.0/1.0/cdr-container/panw-cdr-container.sh ./panw-cdr-container.sh

# Verify the integrity of the script (This step is a good practice for security, although it requires a checksum to compare)
# RUN echo "checksum_value_here  panw-cdr-container.sh" | sha256sum -c -

# Make the script executable
RUN chmod +x ./panw-cdr-container.sh

# Run the script when the container starts
CMD ["/bin/bash", "./panw-cdr-container.sh"]