# XMRIG Single container detection senario 
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: miner-threat
    app: xmrig-miner
  name: xmrig-miner-container
spec: # the spec section defines what container will be called in the kuberentes deployment 
  containers:
  - image: zsco/xmrig-docker:latest
    name: miner-threat
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
