# XMRIG Single container detection senario 
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: miner-threat
    app: xmrig-miner
  name: xmrig-miner-container
spec: # the spec section defines what container will be called in the kuberentes deployment 
  containers:
  - image: metal3d/xmrig
    name: miner-threat
    resources: {}
  dnsPolicy: ClusterFirst