# Simple YAML manifest for a Alpine Pod with Prviledges to do an escape to host
apiVersion: v1
kind: Pod
metadata:
  name: escape-demo
  labels:
    app: escape-demo
spec:
  containers:
    - name: con-escaper
      image: alpine 
      securityContext:
        privileged: true
        capabilities:
          add:
            - SYS_ADMIN
            - NET_ADMIN
      volumeMounts:
        - name: host
          mountPath: /host
  volumes:
    - name: host
      hostPath:
        path: /
